### ISSUE TITLE
Build fails for Ubuntu en Suse

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-mssql#2]
### Ansible
Paste the output of `ansible --version` here:
```
  - ansible_version=">=2.2,<2.3"
  - ansible_version=">=2.3,<2.4"
  - ansible_version=">=2.4,<2.5"
```

### Operating system
Paste the output of `cat /etc/*-release`
```
platforms:
  - name: mssql-opensuse-42.3
    image: opensuse:42.3
  - name: mssql-ubuntu-xenial
    image: ubuntu:xenial
```

## What are you seeing?

Ubuntu:
```
The following information may help to resolve the situation:
The following packages have unmet dependencies:
mssql-server-agent : Depends: mssql-server (>= 14.0.405.163-2) but it is not going to be installed
```

Suse:
```
installed mssql-server-14.0.3022.28-2.x86_64 obsoletes mssql-server-agent provided by mssql-server-agent-14.0.3015.40-1.x86_64
```

Maybe specific versions of packages can be installed instead of the latest found in the repository.
